/*
 * FilterManager.java
 *
 * Created on 26 March 2002, 12:10
 */

package gilbert.ui;

import java.util.*;
import org.apache.log4j.*;
import javax.swing.*;
import gilbert.extractor.*;

/**
 * Add an remove filtes from transmutors.
 *
 * @author Daniel Hahn
 * @version CVS $Revision$
 */
public class FilterDialog extends javax.swing.JDialog {
    /// The Tranmutor for the filters
    Object transmutor;
    /// The logger for this class
    Logger logger = Logger.getLogger(this.getClass());
    
    /** Creates new form FilterManager */
    public FilterDialog(java.awt.Frame parent, boolean modal, Object transmutor) {
        super(parent, modal);
        this.transmutor = transmutor;
        initComponents();
        initForm();
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filterList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        remButton = new javax.swing.JButton();
        propertiesButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setViewportView(filterList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel2.add(okButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jPanel4.add(addButton);

        remButton.setText("Remove");
        remButton.setEnabled(false);
        jPanel4.add(remButton);

        propertiesButton.setText("Properties");
        propertiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertiesButtonActionPerformed(evt);
            }
        });

        jPanel4.add(propertiesButton);

        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        pack();
    }//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void propertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesButtonActionPerformed
        Object selection = filterList.getSelectedValue();
        if (selection != null) {
            PropertyEditingDialog propDialog = new PropertyEditingDialog(null, true, selection);
            propDialog.show();
        }
    }//GEN-LAST:event_propertiesButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        ClassSelectDialog selector = null;
        if (transmutor instanceof Refiner) {
            selector = new ClassSelectDialog(null, true, DataHandler.getURLFilters());
        } else {
            selector = new ClassSelectDialog(null, true, DataHandler.getVisitFilters());
        }
        selector.show();
        Object result = selector.getSelection();
        if (result != null && !selector.isCancelled()) {
            if (transmutor instanceof Refiner) {
                ((Refiner) transmutor).addPrefilter((URLFilter) result);
            } else {
                ((Extractor) transmutor).addPrefilter((VisitFilter) result);
            }
            DefaultListModel lm = (DefaultListModel) filterList.getModel();
            lm.addElement(result);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * Intializes this form.
     */
    private void initForm() {
        DefaultListModel listModel = new DefaultListModel();
        filterList.setModel(listModel);
        Vector filters = null;
        if (transmutor instanceof Refiner) {
            filters = ((Refiner) transmutor).getPrefilters();
        } else {
            filters = ((Extractor) transmutor).getPrefilters();
        }
        Enumeration filterE = filters.elements();
        
        while (filterE.hasMoreElements()) {
            listModel.addElement(filterE.nextElement());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList filterList;
    private javax.swing.JButton addButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton remButton;
    private javax.swing.JButton propertiesButton;
    // End of variables declaration//GEN-END:variables

}
